name: Package Build Check

on:
    push:
    pull_request:

jobs:
    build-and-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: pip

            - name: Install build tooling
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine

            - name: Build distributions
              run: |
                  rm -rf dist
                  python -m build

            - name: Validate metadata with Twine
              run: twine check dist/*

            - name: List built artifacts
              if: always()
              run: ls -lh dist/
